"""
TAILOR — Gmail Ingest
Reads email chunks generated by chunk_gmail.py and ingests them into ChromaDB.

Features:
  - Embedding via configured provider (default: nomic-embed-text via Ollama)
  - Embedding prefix for better retrieval: "Email | From: X | To: Y | Subject: Z"
  - Source tag: "email"
  - Incremental: checks if chunks already exist
  - Batches of 10 chunks per embedding call

Usage:
  python3 scripts/9_ingest_gmail.py              # Incremental ingest
  python3 scripts/9_ingest_gmail.py --full       # Re-ingest (deletes existing email chunks)
  python3 scripts/9_ingest_gmail.py --stats      # Statistics
  python3 scripts/9_ingest_gmail.py --dry-run    # Mostra cosa farebbe senza scrivere

Input:  data/chunks_gmail.jsonl
Output: ChromaDB collection (configured in tailor.yaml)
"""

import json
import os
import sys
import time
import chromadb

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR = os.path.join(BASE_DIR, "data")
sys.path.insert(0, os.path.join(BASE_DIR, "scripts", "lib"))
from config import get as cfg
from embedding import get_embeddings as _embed_fn

DB_DIR = cfg("kb", "chromadb_path") or os.path.join(BASE_DIR, "db")

INPUT_FILE = os.path.join(DATA_DIR, "chunks_gmail.jsonl")

COLLECTION_NAME = cfg("kb", "collection") or "tailor_kb"

BATCH_SIZE = 10
MAX_TEXT_CHARS = 4000


# ============================================================
# EMBEDDING (provider-agnostic via config)
# ============================================================

def check_embedding():
    """Verify embedding provider is reachable."""
    provider = cfg("embedding", "provider") or "ollama"
    model = cfg("embedding", "model") or "nomic-embed-text"
    print(f"Embedding: {provider}/{model}")
    try:
        test = get_embeddings(["test"])
        if test is None:
            print("ERROR: embedding provider not reachable.")
            sys.exit(1)
        print(f"Embedding OK — {len(test[0])} dimensions")
    except Exception as e:
        print(f"ERROR: embedding check failed: {e}")
        sys.exit(1)


def get_embeddings(texts):
    """Batch embedding via configured provider."""
    truncated = [t[:MAX_TEXT_CHARS] for t in texts]
    try:
        return _embed_fn(truncated)
    except Exception as e:
        print(f"\nEmbedding error: {e}")
        return None


# ============================================================
# INGEST
# ============================================================

def load_chunks():
    """Load chunks from JSONL file."""
    chunks = []
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                chunks.append(json.loads(line))
    return chunks


def delete_email_chunks(collection):
    """Cancella tutti i chunk con source=email dalla collection."""
    print("Rimozione chunk email esistenti...")
    total_deleted = 0
    batch_size = 500

    while True:
        try:
            results = collection.get(
                where={"source": "email"},
                include=[],
                limit=batch_size,
            )
            if not results["ids"]:
                break
            collection.delete(ids=results["ids"])
            total_deleted += len(results["ids"])
            print(f"  Rimossi {total_deleted:,} chunk...")
        except Exception as e:
            print(f"  Error during deletion: {e}")
            break

    print(f"  Total removed: {total_deleted:,}")
    return total_deleted


def ingest_chunks(collection, chunks, dry_run=False):
    """Scrive chunk in ChromaDB in batch."""
    total = len(chunks)
    processed = 0
    errors = 0
    skipped = 0

    start_time = time.time()

    for batch_start in range(0, total, BATCH_SIZE):
        batch = chunks[batch_start:batch_start + BATCH_SIZE]

        # Prepara testi con prefisso per embedding
        texts = []
        for c in batch:
            prefix = c.get("embed_prefix", "")
            text = c["text"]
            if prefix:
                texts.append(f"{prefix}\n\n{text}")
            else:
                texts.append(text)

        if dry_run:
            processed += len(batch)
            continue

        # Embedding
        embeddings = get_embeddings(texts)
        if embeddings is None:
            errors += len(batch)
            continue

        # Prepara dati per ChromaDB
        ids = [c["chunk_id"] for c in batch]
        documents = [c["text"][:MAX_TEXT_CHARS] for c in batch]
        metadatas = [c["metadata"] for c in batch]

        try:
            collection.upsert(
                ids=ids,
                embeddings=embeddings,
                documents=documents,
                metadatas=metadatas,
            )
        except Exception as e:
            print(f"\n  ChromaDB errore: {e}")
            errors += len(batch)
            continue

        processed += len(batch)

        # Progress
        if processed % 1000 == 0 or processed == total:
            elapsed = time.time() - start_time
            rate = processed / max(1, elapsed)
            eta = (total - processed) / max(1, rate)
            print(f"  {processed:,}/{total:,} — {rate:.1f} chunk/s — ETA {eta:.0f}s")

    return processed, errors, skipped


# ============================================================
# STATS
# ============================================================

def show_stats():
    print(f"\n=== Stats Gmail Ingest ===")

    if os.path.exists(INPUT_FILE):
        count = sum(1 for _ in open(INPUT_FILE))
        size_mb = os.path.getsize(INPUT_FILE) / 1024 / 1024
        print(f"File chunk: {count:,} chunk ({size_mb:.1f} MB)")
    else:
        print("File chunk non trovato.")

    # Conta chunk email in ChromaDB
    try:
        client = chromadb.PersistentClient(path=DB_DIR)
        collection = client.get_collection(name=COLLECTION_NAME)

        # Conta via metadata source=email
        import sqlite3
        conn = sqlite3.connect(os.path.join(DB_DIR, "chroma.sqlite3"))
        cur = conn.cursor()
        cur.execute("""
            SELECT COUNT(DISTINCT id) FROM embedding_metadata
            WHERE key = 'source' AND string_value = 'email'
        """)
        email_count = cur.fetchone()[0]
        conn.close()

        print(f"Chunk email in KB: {email_count:,}")
        print(f"Chunk totali in KB: {collection.count():,}")
    except Exception as e:
        print(f"Error reading KB: {e}")


# ============================================================
# MAIN
# ============================================================

def main():
    full_mode = "--full" in sys.argv
    dry_run = "--dry-run" in sys.argv
    stats_mode = "--stats" in sys.argv

    if stats_mode:
        show_stats()
        return

    print(f"TAILOR Gmail Ingest")
    print(f"Input: {INPUT_FILE}")

    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: file not found. Run chunk_gmail.py first.")
        sys.exit(1)

    # Load chunks
    chunks = load_chunks()
    print(f"Chunk da ingestare: {len(chunks):,}")

    if not chunks:
        print("No chunks to ingest.")
        return

    if dry_run:
        print(f"\n[DRY RUN] Nessuna scrittura in ChromaDB")
        print(f"  Chunk che verrebbero scritti: {len(chunks):,}")
        total_chars = sum(c["metadata"]["char_count"] for c in chunks)
        print(f"  Chars totali: {total_chars:,}")
        print(f"  Tempo stimato embedding: ~{len(chunks) / 50:.0f}s")
        return

    # Setup
    check_embedding()
    os.makedirs(DB_DIR, exist_ok=True)
    client = chromadb.PersistentClient(path=DB_DIR)
    collection = client.get_collection(name=COLLECTION_NAME)

    print(f"Chunk attuali in KB: {collection.count():,}")

    # Full mode: cancella chunk email esistenti
    if full_mode:
        delete_email_chunks(collection)

    # Ingest
    mode = "FULL RE-INGEST" if full_mode else "INCREMENTALE"
    print(f"\nMode: {mode}")
    print(f"Ingest in corso...\n")

    start = time.time()
    processed, errors, skipped = ingest_chunks(collection, chunks)
    elapsed = time.time() - start

    print(f"\n{'='*50}")
    print(f"Result:")
    print(f"  Chunk processati: {processed:,}")
    print(f"  Errori: {errors:,}")
    print(f"  Tempo: {elapsed:.1f}s ({processed / max(1, elapsed):.1f} chunk/s)")
    print(f"  Total chunks in KB: {collection.count():,}")


if __name__ == "__main__":
    main()